CREATE TABLE IF NOT EXISTS hidden_rating
(
    guid INT(11) UNSIGNED NOT NULL PRIMARY KEY,
    rating2 INT(10) UNSIGNED NOT NULL DEFAULT 1500,
    rating3 INT(10) UNSIGNED NOT NULL DEFAULT 1500,
    rating5 INT(10) UNSIGNED NOT NULL DEFAULT 1500
);

INSERT INTO hidden_rating(guid) SELECT DISTINCT guid FROM arena_team_member;