UPDATE creature_template SET ScriptName = "mob_bonechewer_behemoth" WHERE entry = 23196;
UPDATE creature_template SET ScriptName = "mob_bonechewer_shield_disciple" WHERE entry = 23236;
UPDATE creature_template SET ScriptName = "mob_bonechewer_blade_fury" WHERE entry = 23235;
UPDATE creature_template SET ScriptName = "mob_shadowmoon_grunt" WHERE entry = 23147;
UPDATE creature_template SET ScriptName = "mob_bonechewer_blood_prophet" WHERE entry = 23237;
UPDATE creature_template SET ScriptName = "mob_mutated_war_hound" WHERE entry = 23232;
UPDATE creature_template SET ScriptName = "mob_bonechewer_brawler" WHERE entry = 23222;
UPDATE creature_template SET ScriptName = "mob_bonechewer_combatant" WHERE entry = 23239;
UPDATE creature_template SET ScriptName = "mob_bonechewer_spectator" WHERE entry = 23223;