UPDATE `creature_template` SET `name` = 'Quest - The Vengeful Harbringer - Script Trigger', `ScriptName` = 'quest_the_vengeful_harbringer' WHERE `creature_template`.`entry` = 21445;
UPDATE creature SET position_x = '-2972.703857', position_y = '4406.644531', position_z = '-49.229435', orientation = '4.804782' WHERE guid = '75116';
INSERT INTO `creature_template` (`entry`, `heroic_entry`, `KillCredit`, `modelid_A`, `modelid_A2`, `modelid_H`, `modelid_H2`, `name`, `subname`, `IconName`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `baseattacktime`, `rangeattacktime`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `class`, `race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `RacialLeader`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES
(21431, 0, NULL, 16480, 11686, 16480, 11686, 'Bone Wastes - Defender Trigger 01', NULL, NULL, 60, 60, 6900, 6900, 0, 0, 20, 114, 114, 0, 1.125, 1, 0, 0, 0, 0, 0, 0, 0, 33554688, 0, 0, 0, 0, 0, 0, 0, 0, 100, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, '', 0, 3, 0, 1, 0, 0, 130, '');
INSERT INTO `creature_template` (`entry`, `heroic_entry`, `KillCredit`, `modelid_A`, `modelid_A2`, `modelid_H`, `modelid_H2`, `name`, `subname`, `IconName`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `baseattacktime`, `rangeattacktime`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `class`, `race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `RacialLeader`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES
(21433, 0, NULL, 16480, 11686, 16480, 11686, 'Quest - The Vengeful Harbringer - Trash Portal', NULL, NULL, 60, 60, 6900, 6900, 0, 0, 20, 114, 114, 0, 1.125, 1, 0, 0, 0, 0, 0, 0, 0, 33554688, 0, 0, 0, 0, 0, 0, 0, 0, 100, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, '', 0, 3, 0, 1, 0, 0, 130, '');
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES
('XXX', 21431, 530, 1, 0, 0, -2971.2, 4341.08, -49.7973, 1.57286, 300, 0, 0, 6900, 0, 0, 0);
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES
('XXX', 21433, 530, 1, 0, 0, -2972.67, 4405.69, -49.2297, 4.7498, 300, 0, 0, 5000, 0, 0, 0);
UPDATE creature SET position_x = '-2974.434570', position_y = '4338.480957', position_z = '-30.378220', orientation = '5.524985' WHERE guid = '75116';
UPDATE `creature_template` SET `faction_A` = '1678', `faction_H` = '1678', `speed` = '0.5' WHERE `creature_template`.`entry` = 21636;
UPDATE `creature_template` SET `faction_A` = '35', `faction_H` = '35', `speed` = '0.5' WHERE `creature_template`.`entry` = 22285;
UPDATE `creature_template` SET `faction_A` = '1678', `faction_H` = '1678', `speed` = '0.5' WHERE `creature_template`.`entry` = 21638;
UPDATE `creature_template` SET `ScriptName` = 'mob_vengeful_draenei' WHERE `creature_template`.`entry` = 21636;
UPDATE `creature_template` SET `ScriptName` = 'mob_vengeful_draenei' WHERE `creature_template`.`entry` = 21638;
UPDATE `creature_template` SET `minhealth` = '8000', `maxhealth` = '8000' WHERE `creature_template`.`entry` = 21445;

INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES
('XXX', 21489, 530, 1, 0, 0, -2968.56, 4379.37, -49.2288, 4.76871, 300, 0, 0, 6900, 0, 0, 0);
DELETE FROM `creature_involvedrelation` WHERE `id`=21638;

INSERT INTO `creature_equip_template` (`entry`, `equipmodel1`, `equipmodel2`, `equipmodel3`, `equipinfo1`, `equipinfo2`, `equipinfo3`, `equipslot1`, `equipslot2`, `equipslot3`) VALUES
(23683, 41561, 0, 0, 285280770, 0, 0, 2, 0, 0);
INSERT INTO `creature_equip_template` (`entry`, `equipmodel1`, `equipmodel2`, `equipmodel3`, `equipinfo1`, `equipinfo2`, `equipinfo3`, `equipslot1`, `equipslot2`, `equipslot3`) VALUES
(23684, 40914, 0, 0, 285280770, 0, 0, 2, 0, 0);
UPDATE `creature_template` SET `equipment_id` = '23683' WHERE `creature_template`.`entry` = 21638;
UPDATE `creature_template` SET `equipment_id` = '23684' WHERE `creature_template`.`entry` = 21636;
INSERT INTO `world`.`gameobject_involvedrelation` (
`id` ,
`quest`
)
VALUES (
'184830', '10842'
);

DELETE FROM `quest_template` WHERE `entry`=10842;
INSERT INTO `quest_template` (`entry`, `Method`, `ZoneOrSort`, `SkillOrClass`, `MinLevel`, `QuestLevel`, `Type`, `RequiredRaces`, `RequiredSkillValue`, `RepObjectiveFaction`, `RepObjectiveValue`, `RequiredMinRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepFaction`, `RequiredMaxRepValue`, `SuggestedPlayers`, `LimitTime`, `QuestFlags`, `SpecialFlags`, `CharTitleId`, `PrevQuestId`, `NextQuestId`, `ExclusiveGroup`, `NextQuestInChain`, `SrcItemId`, `SrcItemCount`, `SrcSpell`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqSourceId1`, `ReqSourceId2`, `ReqSourceId3`, `ReqSourceId4`, `ReqSourceCount1`, `ReqSourceCount2`, `ReqSourceCount3`, `ReqSourceCount4`, `ReqSourceRef1`, `ReqSourceRef2`, `ReqSourceRef3`, `ReqSourceRef4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOId4`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `ReqCreatureOrGOCount4`, `ReqSpellCast1`, `ReqSpellCast2`, `ReqSpellCast3`, `ReqSpellCast4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewHonorableKills`, `RewOrReqMoney`, `RewMoneyMaxLevel`, `RewSpell`, `RewSpellCast`, `RewMailTemplateId`, `RewMailDelaySecs`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `StartScript`, `CompleteScript`) VALUES
(10842, 1, 3519, 0, 63, 65, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 128, 2, 0, 10849, 0, 0, 0, 30527, 1, 0, 'The Vengeful Harbinger', 'The Tomb of Lights has become corrupted by the Shadow Council and the draenei dead have become cursed spirits, angry and confused with a burning hatred for the living.  $B$BBefore I left Shattrath I was given a draenei tomb relic.  It can be used near the Ancient Draenei Altar deep within the Tomb of Lights to summon a tomb guardian.  This creature will activate the altar and will begin to purge the tomb of corrupt spirits, freeing them to ascend.  Protect the tomb guardian until the ritual is complete.', 'High Priest Orglum wants you to journey into the Tomb of Lights and use the Draenei Tomb Relic near the Ancient Draenei Altar.$B$BDefend the Tomb Guardian and defeat the Vengeful Harbinger.  When the ritual is complete, speak with the Draenei Ascendant at the Ancient Draenei Altar.', 'You cannot know what you have done here $N. You have saved so many of us from an eternity of darkness. There is little that I can do for the living and nothing that I could give that would thank you enough. Take what seems useful to you.', 'You have saved us all. What can we do to thank you?', '', 'Defend The Tomb Guardian', '', '', '', 30527, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21638, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 31617, 31615, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1011, 0, 0, 0, 0, 250, 0, 0, 0, 0, 0, 0, 82500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_template` (`entry`, `heroic_entry`, `KillCredit`, `modelid_A`, `modelid_A2`, `modelid_H`, `modelid_H2`, `name`, `subname`, `IconName`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `baseattacktime`, `rangeattacktime`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `class`, `race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `RacialLeader`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES
(66012, 0, NULL, 16480, 11686, 16480, 11686, 'Quest - The Vengeful Harbringer - Corpse Move Trigger', NULL, NULL, 60, 60, 6900, 6900, 0, 0, 20, 114, 114, 0, 1.125, 1, 0, 0, 0, 0, 0, 0, 0, 33554688, 0, 0, 0, 0, 0, 0, 0, 0, 100, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, '', 0, 3, 0, 1, 0, 0, 130, '');



INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES
('XXX', 66012, 530, 1, 0, 0, -2970.45, 4334.46, -34.7286, 2.41898, 300, 0, 0, 6900, 0, 0, 0);




